name: Deploy FinTech App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: 206.189.57.159
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/portfolio-server/MINI-FINTECH-LOAN-SYSTEM
            git pull origin main
            cd ~/portfolio-server
            docker compose up --build -d fintech-frontend fintech-backend
            docker system prune -f